version: '3.9'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-connexly}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-connexly}
      POSTGRES_DB: ${POSTGRES_DB:-whatsapp_connexly_prod}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - connexly-network
    restart: unless-stopped

  # Redis for caching and queues
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - connexly-network
    restart: unless-stopped

  # Web Application
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-connexly}:${POSTGRES_PASSWORD:-connexly}@db:5432/${POSTGRES_DB:-whatsapp_connexly_prod}
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      - WHATSAPP_CONFIG_ID=${WHATSAPP_CONFIG_ID}
    depends_on:
      - db
      - redis
    networks:
      - connexly-network
    restart: unless-stopped
    volumes:
      - ./apps/web/.env.local:/app/.env.local:ro

  # Nginx Reverse Proxy (for SSL termination and webhook handling)
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - connexly-network
    restart: unless-stopped

  # Worker Service for background jobs
  worker:
    build:
      context: ./services/worker
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-connexly}:${POSTGRES_PASSWORD:-connexly}@db:5432/${POSTGRES_DB:-whatsapp_connexly_prod}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - connexly-network
    restart: unless-stopped

volumes:
  db_data:
  redis_data:

networks:
  connexly-network:
    driver: bridge
